### PR TITLE
feat: support min_coverage

### PR DESCRIPTION
**Pull request by omartinma**
## Description

Supports min_coverage property of very_good_coverage

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
@omartinma why are we making this change? Ideally projects at VGV should all have a min_coverage of 100 and we can use coverage_excludes to exclude things like generated code.

**Review by felangel — CHANGES_REQUESTED** [review]
Can we also update the documentation in the README to include the new input?

**Comment by kzawadi** [comment]
hahaahh.. was about to look for a feature request template to file for this feature ..I love the community ❤️🙌

**Comment by yeikel16** [comment]
It would be cool if it came out in the next version, I would like to use it in my project, I am working on the coverage but I still haven't reached 100, that's why this configuration is necessary

**Comment by kzawadi** [comment]
> It would be cool if it came out in the next version, I would like to use it in my project, I am working on the coverage but I still haven't reached 100, that's why this configuration is necessary

Exactly. It kinder hinder rapid development ..though it should be 100% by default until you shoot your foot by specifying the min_covergae 😂

**Review by felangel — APPROVED** [review]

**Pull request merged**
